- hosts: all
  become: true
  roles:
    - role: nephelaiio.unifi_controller
    - role: ser2net
      vars:
        ports:
          - device: /dev/ttyUSB0
            baud: 115200
            tcpport: 6638
            state: raw
            timeout: 600
          - device: /dev/ttyAMA0
            baud: 38400
            tcpport: 2000
            state: raw
            timeout: 600
  vars:
    unifi_java_packages: openjdk-8-jre-headless
    unifi_java_home: /usr/lib/jvm/java-8-openjdk-armhf/jre