---
- name: install ser2net
  apt:
    name: ser2net
    state: present

- name: config ser2net
  template:
    src: templates/ser2net.conf.j2
    dest: /etc/ser2net.conf
    owner: root
    group: root
    mode: 0644
  #notify: restart ser2net

- name: create log dir
  file:
    path: /var/log/ser2net
    state: directory
    owner: root
    group: root
    mode: 0755

- name: start ser2net
  service:
    name: ser2net
    state: started
    enabled: true
  notify: restart ser2net